import { randomBytes } from 'crypto';
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import { uploadBuffer } from '@/lib/r2';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica', color: '#1A1D26' },
  header: { backgroundColor: '#F26522', padding: 20, marginBottom: 24, borderRadius: 4 },
  brand: { color: '#FFFFFF', fontSize: 14, fontWeight: 700, marginBottom: 4 },
  title: { color: '#FFFFFF', fontSize: 20, fontWeight: 700 },
  subtitle: { color: '#FFFFFF', fontSize: 11, marginTop: 4, opacity: 0.9 },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E8ECF1',
  },
  label: { color: '#5A6178', fontSize: 11 },
  value: { color: '#1A1D26', fontSize: 11, fontWeight: 700 },
  disclaimer: { marginTop: 32, fontSize: 9, color: '#8C93A7', lineHeight: 1.5 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 9, color: '#8C93A7', textAlign: 'center' },
});

export interface PDFRow {
  label: string;
  value: string;
}

export interface GenerateToolPDFParams {
  title: string;
  subtitle?: string;
  rows: PDFRow[];
  disclaimer?: string;
  r2KeyPrefix: string; // e.g. 'pdfs/tax-calculator'
}

function ToolResultDocument({ title, subtitle, rows, disclaimer }: GenerateToolPDFParams) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>GCCStartup</Text>
          <Text style={styles.title}>{title}</Text>
          {subtitle && <Text style={styles.subtitle}>{subtitle}</Text>}
        </View>

        {rows.map((row, idx) => (
          <View key={idx} style={styles.row}>
            <Text style={styles.label}>{row.label}</Text>
            <Text style={styles.value}>{row.value}</Text>
          </View>
        ))}

        {disclaimer && <Text style={styles.disclaimer}>{disclaimer}</Text>}

        <Text style={styles.footer}>
          Generated by GCCStartup — {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}

export async function generateToolPDF(params: GenerateToolPDFParams): Promise<{ r2Key: string }> {
  const buffer = await renderToBuffer(<ToolResultDocument {...params} />);
  const r2Key = `${params.r2KeyPrefix}/${Date.now()}-${randomBytes(4).toString('hex')}.pdf`;
  await uploadBuffer(r2Key, buffer, 'application/pdf');
  return { r2Key };
}
