import { NextResponse } from 'next/server';
import { eq } from 'drizzle-orm';
import { db } from '@/lib/db';
import { leads } from '@/lib/db/schema';
import { generateToolPDF, type PDFRow } from '@/lib/pdf';
import { getPresignedDownloadUrl } from '@/lib/r2';
import { sendToolResultEmail } from '@/lib/email';

interface GeneratePDFRequest {
  lead_id: string;
  title: string;
  subtitle?: string;
  rows: PDFRow[];
  email_it?: boolean;
}

const DISCLAIMER =
  'This document is an estimate generated by an automated tool and does not constitute filed tax, legal, or financial advice. Consult a licensed advisor before relying on these figures.';

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as GeneratePDFRequest;
    const { lead_id, title, subtitle, rows, email_it } = body;

    if (!lead_id || !title || !rows?.length) {
      return NextResponse.json({ error: 'lead_id, title, and rows are required' }, { status: 400 });
    }

    const [lead] = await db.select().from(leads).where(eq(leads.id, lead_id)).limit(1);
    if (!lead) {
      return NextResponse.json({ error: 'Lead not found' }, { status: 404 });
    }

    const { r2Key } = await generateToolPDF({
      title,
      subtitle,
      rows,
      disclaimer: DISCLAIMER,
      r2KeyPrefix: `pdfs/${lead.source_tool}`,
    });

    await db.update(leads).set({ pdf_r2_key: r2Key }).where(eq(leads.id, lead.id));

    const downloadUrl = await getPresignedDownloadUrl(r2Key, 60 * 60 * 24 * 7); // 7 days

    if (email_it && lead.email) {
      await sendToolResultEmail(lead.email, title, downloadUrl);
    }

    return NextResponse.json({ url: downloadUrl });
  } catch (error) {
    console.error('[api/pdf/generate] Error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
