import { NextRequest, NextResponse } from 'next/server';
import { eq } from 'drizzle-orm';
import { getServerSession } from '@/lib/session';
import { db } from '@/lib/db';
import { companies, users } from '@/lib/db/schema';
import { randomBytes } from 'crypto';
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import { uploadBuffer } from '@/lib/r2';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica', color: '#1A1D26' },
  header: { backgroundColor: '#0A2540', padding: 20, marginBottom: 24, borderRadius: 4 },
  brand: { color: '#C9A84C', fontSize: 14, fontWeight: 700, marginBottom: 4 },
  title: { color: '#FFFFFF', fontSize: 20, fontWeight: 700 },
  subtitle: { color: '#FFFFFF', fontSize: 11, marginTop: 4, opacity: 0.9 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 12, fontWeight: 700, color: '#0A2540', marginBottom: 8, borderBottomWidth: 1, borderBottomColor: '#E8ECF1', paddingBottom: 4 },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: '#F1F3F7' },
  label: { color: '#5A6178', fontSize: 10 },
  value: { color: '#1A1D26', fontSize: 10, fontWeight: 700 },
  statusBadge: { backgroundColor: '#16A34A', color: '#FFFFFF', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, fontSize: 10, fontWeight: 700, alignSelf: 'flex-start' as const },
  statusOverdue: { backgroundColor: '#DC2626', color: '#FFFFFF', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, fontSize: 10, fontWeight: 700, alignSelf: 'flex-start' as const },
  disclaimer: { marginTop: 32, fontSize: 9, color: '#8C93A7', lineHeight: 1.5 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 9, color: '#8C93A7', textAlign: 'center' },
});

function GoodStandingDocument({
  companyName,
  jurisdiction,
  tier,
  status,
  incorporationDate,
  tradeLicenseNumber,
  expiryDate,
}: {
  companyName: string;
  jurisdiction: string;
  tier: string;
  status: string;
  incorporationDate: string;
  tradeLicenseNumber: string | null;
  expiryDate: string;
}) {
  const isActive = status === 'active';
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>GCCStartup</Text>
          <Text style={styles.title}>Certificate of Good Standing</Text>
          <Text style={styles.subtitle}>Company Status Summary — {new Date().toLocaleDateString()}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>COMPANY DETAILS</Text>
          <View style={styles.row}><Text style={styles.label}>Company Name</Text><Text style={styles.value}>{companyName}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Jurisdiction</Text><Text style={styles.value}>{jurisdiction}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Package</Text><Text style={styles.value}>{tier}</Text></View>
          {tradeLicenseNumber && <View style={styles.row}><Text style={styles.label}>Trade License No.</Text><Text style={styles.value}>{tradeLicenseNumber}</Text></View>}
          <View style={styles.row}><Text style={styles.label}>Incorporation Date</Text><Text style={styles.value}>{incorporationDate}</Text></View>
          <View style={styles.row}><Text style={styles.label}>License Expiry</Text><Text style={styles.value}>{expiryDate}</Text></View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>CURRENT STATUS</Text>
          <View style={{ marginTop: 8, marginBottom: 12 }}>
            <Text style={isActive ? styles.statusBadge : styles.statusOverdue}>
              {isActive ? '● ACTIVE — IN GOOD STANDING' : '● ' + status.toUpperCase()}
            </Text>
          </View>
          <Text style={{ fontSize: 10, color: '#5A6178', lineHeight: 1.5 }}>
            {isActive
              ? `This confirms that ${companyName} is registered and in active status with the relevant authorities as of the date above. The company is compliant with all filing and renewal requirements.`
              : `This company's status is "${status}". Please contact your account manager for details on required actions to restore good standing.`}
          </Text>
        </View>

        <Text style={styles.disclaimer}>
          This is a system-generated summary and does not constitute an official government certificate of good standing.
          For official documents, please contact your GCCStartup account manager.
        </Text>

        <Text style={styles.footer}>
          Generated by GCCStartup Portal — {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}

export async function GET(req: NextRequest) {
  const session = await getServerSession();
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const companyId = req.nextUrl.searchParams.get('companyId');

  const [company] = companyId
    ? await db.select().from(companies).where(eq(companies.id, companyId)).limit(1)
    : await db.select().from(companies).where(eq(companies.user_id, session.userId)).orderBy(companies.created_at).limit(1);

  if (!company) return NextResponse.json({ error: 'No company found' }, { status: 404 });
  if (company.user_id !== session.userId) return NextResponse.json({ error: 'Forbidden' }, { status: 403 });

  const buffer = await renderToBuffer(
    <GoodStandingDocument
      companyName={company.company_name}
      jurisdiction={company.jurisdiction.replace('-', ' ').replace(/\b\w/g, (c) => c.toUpperCase())}
      tier={company.tier.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())}
      status={company.status}
      incorporationDate={company.incorporation_date?.toLocaleDateString() ?? 'In Progress'}
      tradeLicenseNumber={company.trade_license_number}
      expiryDate={company.license_expiry_date?.toLocaleDateString() ?? '—'}
    />
  );

  const r2Key = `pdfs/good-standing/${session.userId}/${company.id}-${Date.now()}.pdf`;
  await uploadBuffer(r2Key, buffer, 'application/pdf');

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="good-standing-${company.company_name.replace(/\s+/g, '-').toLowerCase()}.pdf"`,
    },
  });
}